[platformio]
# On charge le fichier secret au niveau global du projet pour que PlatformIO le lise en premier
extra_configs = private_config.ini

[env:giga_r1_m7]
platform = ststm32
board = giga_r1_m7
framework = arduino
monitor_speed = 9600

lib_ldf_mode = deep+
board_upload.maximum_size = 1572864

# CORRECTIF LOGS & WIFI : On fusionne vos flags existants avec ceux du fichier secret
build_flags = 
    -Wno-implicit-fallthrough
    -Wno-vla
    -Wno-sign-compare
    ${wifi_credentials.build_flags}

# CORRECTIF ARCHITECTURE : On dit à PlatformIO que le dossier "taches" 
# contient lui-même des sous-bibliothèques indépendantes.
lib_extra_dirs = 
    lib/taches
    lib/drivers
