[env:giga_r1_m7]
platform = ststm32
board = giga_r1_m7
framework = arduino
monitor_speed = 9600

lib_ldf_mode = deep+
board_upload.maximum_size = 1572864

# CORRECTIF LOGS : Masque les avertissements spécifiques des bibliothèques système d'Arduino
build_flags = 
    -Wno-implicit-fallthrough
    -Wno-vla
    -Wno-sign-compare

# CORRECTIF ARCHITECTURE : On dit à PlatformIO que le dossier "taches" 
# contient lui-même des sous-bibliothèques indépendantes.
lib_extra_dirs = 
    lib/taches
    lib/drivers